#!/bin/bash

NETRC_FILE=~/.netrc

if [ ! -f "$NETRC_FILE" ]; then
  echo -e "${RED}Cannot find "${NETRC_FILE}", please configure your credentials.${DEFAULT}"
  exit 1
fi

if ! grep -q "machine github.com" $NETRC_FILE; then
  echo -e "${RED}Cannot find github.com in "${NETRC_FILE}", please configure your credentials.${DEFAULT}"
  exit 1
fi

# Do an npm install
echo -e "${CYAN}Installing npm packages.${DEFAULT}"
npm install

# Start Docker
echo -e "${CYAN}Starting docker.${DEFAULT}"
open -g -a Docker
while ! docker ps > /dev/null 2>&1 ; do sleep 2; done

# Stop all active containers.
echo -e "${CYAN}Stopping the current active containers.${DEFAULT}"
docker-compose down --volumes > /dev/null 2>&1
docker stop $(docker ps -aq) > /dev/null 2>&1

# Up the docker containers
echo -e "${CYAN}Installing database container.${DEFAULT}"
DOCKER_HOST_IP=`ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | sed -n 1p` docker-compose up -d --build mysql-main-database
sleep 10

echo -e  "${CYAN}Installing back- and frontend containers.${DEFAULT}"
DOCKER_HOST_IP=`ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | sed -n 1p` docker-compose up -d --build frontend-ticker backend-ticker
