version: '3.7'

services:
  mysql-main-database:
    container_name: ticker-mysql-main-database
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ticker
    ports:
      - 3306:3306

  mysql-integration-tests:
    container_name: ticker-mysql-integration-tests
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: ${INTEGRATION_DATABASE_PASSWORD}
      MYSQL_DATABASE: ticker
    ports:
      - 0.0.0.0:3307:3307

  frontend-ticker:
    container_name: ticker-frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - '8080:8080'

  backend-ticker:
    container_name: ticker-backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - '3000:3000'
