version: '3.7'

services:
  mysql-main-database:
    container_name: ticker-mysql-main-database
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ticker
    ports:
      - 3306:3306

  mysql-acceptance-tests:
    container_name: ticker-mysql-acceptance-tests
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: ${ACCEPTANCE_DATABASE_PASSWORD}
      MYSQL_DATABASE: ticker
    ports:
      - 3307:3306

  frontend-ticker:
    container_name: ticker-frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/app

  backend-ticker:
    container_name: ticker-backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
